name: Android Recovery Action
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

env:
  MANIFEST: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1"
  DT_LINK: "https://github.com/juic3b0x/twrp12_device_motorola_denver.git"
  VENDOR: "motorola"
  CODENAME: "denver"
  TZ: "America/Chicago" # Set Time-Zone According To Your Region

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Build Image
      uses: XenonTheInertG/android-recovery-action@main